compareToleranceEpsilon=1e-3
iterations=1e4
powerMethodEpsilon=1e-7
debug=False
maxU = 12
uValues=range(0,22)
stepKByZoomIn = 5
kValuesZoomIn=range(1,41, stepKByZoomIn)
stepKByZoomOut = 40
kValuesZoomOut = range(1,320, stepKByZoomOut)
uPca=range(0, maxU) # check which values terminan siendo
startUpUValue=10
optimumUValue=5